from pathlib import Path

MODEL_PATH = Path("mujoco_menagerie/franka_emika_panda/scene.xml")
RESULTS_DIR = Path("results")
SCENARIOS = ("hit_floor", "push_block", "peg_in_hole")
FORCE_VISUAL_MODES = ("arrow", "ring", "both")
AUDIO_MODES = ("contact", "geiger", "both")
OCCLUDER_STYLES = ("solid", "frosted")

DEFAULT_CUSHION_THRESHOLD = 100.0
DEFAULT_IMPEDANCE_KP = 300.0
DEFAULT_IMPEDANCE_DP = 35.0
DEFAULT_IMPEDANCE_KR = 20.0
DEFAULT_IMPEDANCE_DR = 4.0
DEFAULT_IMPEDANCE_TORQUE_LIMIT = 30.0
DEFAULT_HOLE_CLEARANCE_MM = 8.0
DEFAULT_PEG_ALPHA = 1.0
DEFAULT_SOCKET_ALPHA = 1.0
DEFAULT_OCCLUDER_ALPHA = 1.0
DEFAULT_OCCLUDER_STYLE = "solid"
DEFAULT_TELEOP_SPEED = 0.06
DEFAULT_TELEOP_NUDGE_STEP = 0.005
DEFAULT_HOLD_TELEOP = False
DEFAULT_ACTUATOR_BOOST = 4.0
DEFAULT_OCCLUDED_HOLE_X_RANGE = (0.0, 0.025)
DEFAULT_OCCLUDED_HOLE_Y_RANGE = (-0.020, 0.020)
DEFAULT_AUDIO_CONTACT_THRESHOLD = 2.0
DEFAULT_AUDIO_LATERAL_THRESHOLD = 5.0
DEFAULT_AUDIO_LATERAL_MAX = 200.0
DEFAULT_AUDIO_VOLUME = 0.35
DEFAULT_MAX_TRIAL_DURATION_S = 150.0
DEFAULT_HEADLESS_DURATION_S = 10.0
DEFAULT_FORCE_THRESHOLD_N = 100.0
DEFAULT_JAMMING_THRESHOLD_N = 50.0

VIDEO_FPS = 30
VIDEO_WIDTH = 960
VIDEO_HEIGHT = 540
